### ISSUE TITLE
Error Parsing Required Array with JSON Schema draft-04

### ISSUE THREAD

**Issue by gurumeditator** [atomicbits/scraml#58] opened 2016-03-11 19:22 UTC
Given an inline schema definition:

...
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "data": {
                    "type": "array",
                    "items":
                      {
                        "type"        :"object",
                        "required": [
                          "name",
                          "typeName",
                          "placeList"
                        ]
...

I am receiving the following error when attempting to generate a client:

error: value has incorrect type (found array, expected one of [boolean])
    level: "error"
    domain: "syntax"
    schema: {"loadingURI":"#","pointer":""}
    keyword: "required"
    found: "array"
    expected: ["boolean"]

**Comment by rigolepe** [comment] 2016-03-11 22:32
Hello,

How about this schema definition?

{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "id": "http://gurumeditator.io/schema/my-object.json",
  "type": "object",
  "properties": {
    "data": {
      "type": "array",
      "items": {
        "id": "http://gurumeditator.io/schema/my-other-object.json",
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "required": true
          },
          "typeName": {
            "type": "string",
            "required": true
          },
          "placeList": {
            "type": "string",
            "required": true
          }
        }
      }
    }
  }
}

According to the json-schema specs, you should give your json-schema definition of objects a proper “id” field. Your sample exposed a bug in scraml when using the json-schema draft-04 on the “required” field. From draft-04 on the required fields should be arrays, like you did. In draft-03 it’s still like in my example above. I’ll look into that soon to fix it. 

Have fun using scraml!

Cheers,
   Peter

**Comment by gurumeditator** [comment] 2016-03-14 12:47
Thank you so much for all of your efforts to this fantastic and very needed project!!

**Comment by rigolepe** [comment] 2016-03-18 12:54
It appears that the error you got was caused by the java-raml-parser on which the project currently relies for RAML parsing. Although json-schema parsing is done with our own library, we see that the java-raml-parser tries to validate the json schemas as soon as "$schema": "http://json-schema.org/draft-04/schema" is provided rather than draft-03. It's not clear why that is and especially not why it gives you that error since it should be valid to enter the required fields as you do. 

That said, we won't be having this problem as soon as we switch to our own raml parser. We're working on our own parser to have more control when moving to RAML 1.0. In this light, I will close this ticket and test it again when our raml parser is finished.

**Closed** 2016-03-18 12:55 UTC
Labels: bug
